name: Merge and Upload Code coverage
on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  upload_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download x86_64 coverage data
        uses: actions/download-artifact@v4
        with:
          name: coverage-x86_64
#      - name: Download arm64 coverage data
#        uses: actions/download-artifact@v4
#        with:
#          name: coverage-aarch64
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
#          token: 6980efe5-a813-451f-ac36-749022ce30f4 # todo: delete token after test !!!
      - name: Skipping build for PR
        if: ${{ github.event_name == 'pull_request' && matrix.runner != 'garm-jammy' && matrix.libc != 'gnu' }}
        run: echo "Skipping build for PR"
